snapshot of project "tin-beta", label v1_5_1

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -18,6 +18,14 @@ AC_INIT(include/tin.h)
 AC_CONFIG_HEADER(include/autoconf.h:include/autoconf.hin)
 AC_PREFIX_DEFAULT(/usr/local)
 
+dnl PACKAGE is required for GNU gettext
+PACKAGE=tin
+VERSION=1.5.1
+AC_DEFINE_UNQUOTED(PACKAGE, "$PACKAGE")
+AC_DEFINE_UNQUOTED(VERSION, "$VERSION")
+AC_SUBST(PACKAGE)
+AC_SUBST(VERSION)
+					
 CF_CHECK_CACHE
 
 CF_WITH_PATH(install-prefix,
@@ -46,6 +54,9 @@ case "$host_os" in
 		;;
 esac
 
+###     Native Language Support
+ALL_LINGUAS=""
+
 ###	Checks for programs.
 save_CFLAGS="$CFLAGS"
 AC_PROG_CC
@@ -55,6 +66,7 @@ AC_PROG_INSTALL
 AC_PROG_RANLIB
 CF_PROG_YACC
 AC_CHECK_PROGS(LINT, lint alint lclint tdlint, [])
+AC_ISC_POSIX
 CF_ANSI_CC_REQD
 CF_PROG_EXT
 CF_LIB_PREFIX(LIB_PREFIX)
@@ -93,6 +105,9 @@ else
 	fi
 fi
 fi
+
+CF_WITH_PROGRAM(gpg,
+[  --with-gpg              (default: from system path)])
 
 ### check for this early, since it'll override several options
 AC_MSG_CHECKING(if NNTP-support will be used)
@@ -467,6 +482,234 @@ CF_WITH_PATH(defaults-dir,
 AC_MSG_RESULT($TIN_DEFAULTS_DIR)
 AC_DEFINE_UNQUOTED(TIN_DEFAULTS_DIR,"$TIN_DEFAULTS_DIR")
 
+### check for ipv6 support
+AC_MSG_CHECKING([whether to enable ipv6])
+AC_ARG_ENABLE(ipv6,
+ [  --enable-ipv6           Enable ipv6 (with ipv4) support (default: disabled)],
+ [ case "$enableval" in
+   no)
+        AC_MSG_RESULT(no)
+        ipv6=no
+        ;;
+   *)
+        AC_MSG_RESULT(yes)
+        AC_DEFINE(ENABLE_IPV6)
+        ipv6=yes
+        ;;
+   esac ],ipv6=no)
+
+ ipv6type=unknown
+ ipv6lib=none
+ ipv6trylibc=no
+
+ if test "$ipv6" = "yes"; then
+       AC_MSG_CHECKING([ipv6 stack type])
+       for i in inria kame linux-glibc linux-libinet6 toshiba v6d zeta; do
+               case $i in
+               inria)
+                       dnl http://www.kame.net/
+                       AC_EGREP_CPP(yes, [dnl
+ #include <netinet/in.h>
+ #ifdef IPV6_INRIA_VERSION
+ yes
+ #endif],
+                               [ipv6type=$i])
+                       ;;
+               kame)
+                       dnl http://www.kame.net/
+                       AC_EGREP_CPP(yes, [dnl
+ #include <netinet/in.h>
+ #ifdef __KAME__
+ yes
+ #endif],
+                               [ipv6type=$i;
+                               ipv6lib=inet6;
+                               ipv6libdir=/usr/local/v6/lib;
+                               ipv6trylibc=yes])
+                       ;;
+               linux-glibc)
+                       dnl http://www.v6.linux.or.jp/
+                       AC_EGREP_CPP(yes, [dnl
+ #include <features.h>
+ #if defined(__GLIBC__) && __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 1
+ yes
+ #endif],
+                               [ipv6type=$i])
+                       ;;
+               linux-libinet6)
+                       dnl http://www.v6.linux.or.jp/
+                       if test -d /usr/inet6 -o -f /usr/include/netinet/ip6.h;
+then
+                               ipv6type=$i
+                               ipv6lib=inet6
+                               ipv6libdir=/usr/inet6/lib
+                               ipv6trylibc=yes;
+                               CFLAGS="-I/usr/inet6/include $CFLAGS"
+                       fi
+                       ;;
+               toshiba)
+                       AC_EGREP_CPP(yes, [dnl
+ #include <sys/param.h>
+ #ifdef _TOSHIBA_INET6
+ yes
+ #endif],
+                               [ipv6type=$i;
+                               ipv6lib=inet6;
+                               ipv6libdir=/usr/local/v6/lib])
+                       ;;
+               v6d)
+                       AC_EGREP_CPP(yes, [dnl
+ #include </usr/local/v6/include/sys/v6config.h>
+ #ifdef __V6D__
+ yes
+ #endif],
+                               [ipv6type=$i;
+                               ipv6lib=v6;
+                               ipv6libdir=/usr/local/v6/lib;
+                               CFLAGS="-I/usr/local/v6/include $CFLAGS"])
+                       ;;
+               zeta)
+                       AC_EGREP_CPP(yes, [dnl
+ #include <sys/param.h>
+ #ifdef _ZETA_MINAMI_INET6
+ yes
+ #endif],
+                               [ipv6type=$i;
+                               ipv6lib=inet6;
+                               ipv6libdir=/usr/local/v6/lib])
+                       ;;
+               esac
+               if test "$ipv6type" != "unknown"; then
+                       break
+               fi
+       done
+       AC_MSG_RESULT($ipv6type)
+ fi
+
+ if test "$ipv6" = "yes" -a "$ipv6lib" != "none"; then
+       if test -d $ipv6libdir -a -f $ipv6libdir/lib$ipv6lib.a; then
+               LIBS="-L$ipv6libdir -l$ipv6lib $LIBS"
+               echo "You have $ipv6lib library, using it"
+       else
+               if test "$ipv6trylibc" = "yes"; then
+                       echo "You do not have $ipv6lib library, using libc"
+               else
+                       echo 'Fatal: no $ipv6lib library found.  cannot continue.'
+                       echo "You need to fetch lib$ipv6lib.a from appropriate"
+                       echo 'ipv6 kit and compile beforehand.'
+                       exit 1
+               fi
+       fi
+ fi
+
+
+ AC_MSG_CHECKING(working getaddrinfo)
+ AC_TRY_RUN([
+ #include <sys/types.h>
+ #include <netdb.h>
+ #include <string.h>
+ #include <sys/socket.h>
+ #include <netinet/in.h>
+
+ main()
+ {
+   int passive, gaierr, inet4 = 0, inet6 = 0;
+   struct addrinfo hints, *ai, *aitop;
+   char straddr[INET6_ADDRSTRLEN], strport[16];
+
+   for (passive = 0; passive <= 1; passive++) {
+     memset(&hints, 0, sizeof(hints));
+     hints.ai_family = AF_UNSPEC;
+     hints.ai_flags = passive ? AI_PASSIVE : 0;
+     hints.ai_socktype = SOCK_STREAM;
+     if ((gaierr = getaddrinfo(NULL, "54321", &hints, &aitop)) != 0) {
+       (void)gai_strerror(gaierr);
+       goto bad;
+     }
+     for (ai = aitop; ai; ai = ai->ai_next) {
+       if (ai->ai_addr == NULL ||
+           ai->ai_addrlen == 0 ||
+           getnameinfo(ai->ai_addr, ai->ai_addrlen,
+                       straddr, sizeof(straddr), strport, sizeof(strport),
+                       NI_NUMERICHOST|NI_NUMERICSERV) != 0) {
+         goto bad;
+       }
+       switch (ai->ai_family) {
+       case AF_INET:
+         if (strcmp(strport, "54321") != 0) {
+           goto bad;
+         }
+         if (passive) {
+           if (strcmp(straddr, "0.0.0.0") != 0) {
+             goto bad;
+           }
+         } else {
+           if (strcmp(straddr, "127.0.0.1") != 0) {
+             goto bad;
+           }
+         }
+         inet4++;
+         break;
+       case AF_INET6:
+         if (strcmp(strport, "54321") != 0) {
+           goto bad;
+         }
+         if (passive) {
+           if (strcmp(straddr, "::") != 0) {
+             goto bad;
+           }
+         } else {
+           if (strcmp(straddr, "::1") != 0) {
+             goto bad;
+           }
+         }
+         inet6++;
+         break;
+       case AF_UNSPEC:
+         goto bad;
+         break;
+       default:
+         /* another family support? */
+         break;
+       }
+     }
+   }
+
+   if (inet6 != 2 || inet4 != 2)
+     goto bad;
+
+   if (aitop)
+     freeaddrinfo(aitop);
+   exit(0);
+
+  bad:
+   if (aitop)
+     freeaddrinfo(aitop);
+   exit(1);
+ }
+ ],
+ AC_MSG_RESULT(yes)
+ buggygetaddrinfo=no,
+ AC_MSG_RESULT(no)
+ buggygetaddrinfo=yes,
+ AC_MSG_RESULT(no)
+ buggygetaddrinfo=yes)
+
+ if test "$buggygetaddrinfo" = "yes"; then
+       if test "$ipv6" = "yes" -a "$ipv6type" != "linux"; then
+               echo 'Fatal: You must get working getaddrinfo() function.'
+               echo '       or you can specify "--disable-ipv6"'.
+               exit 1
+       elif test "$ipv6type" = "linux"; then
+               echo 'Warning: getaddrinfo() implementation on your system seems be buggy.'
+               echo '         Better upgreade your system library to newest version'
+               echo '         of GNU C library (aka glibc).'
+       fi
+ fi
+AC_REPLACE_FUNCS(getaddrinfo getnameinfo)
+
+
+#
 ### checks for operator characteristics (should be the last option)
 AC_MSG_CHECKING(whether to make a coffee while compiling)
 AC_ARG_WITH(coffee,
@@ -482,7 +725,7 @@ AC_ARG_WITH(coffee,
 	esac],
 	AC_MSG_RESULT(no))
 
-###	checks for compiler characteristics
+### checks for compiler characteristics
 CF_MAKEFLAGS
 AC_LANG_C
 AC_C_CONST
@@ -508,6 +751,7 @@ AC_HEADER_DIRENT
 AC_HEADER_TIME
 AC_HEADER_SYS_WAIT
 AC_CHECK_HEADERS(\
+	argz.h \
 	arpa/inet.h \
 	curses.h \
 	errno.h \
@@ -520,6 +764,7 @@ AC_CHECK_HEADERS(\
 	netdb.h \
 	netinet/in.h \
 	netlib.h \
+	nl_types.h \
 	nomacros.h \
 	poll.h \
 	prototypes.h \
@@ -632,7 +877,7 @@ AC_CHECK_FUNCS(\
 	atoi \
 	atol \
 	bcopy \
-	ftime \
+	chmod \
 	fdopen \
 	ftime \
 	getcwd \
@@ -662,8 +907,10 @@ AC_CHECK_FUNCS(\
 	setuid \
 	sigaction \
 	snprintf \
+	stpcpy \
 	strchr \
 	strcasecmp \
+	strdup \
 	strerror \
 	strftime \
 	strpbrk \
@@ -881,6 +1128,10 @@ test ".$cf_cv_good_bcopy" = ".yes" && \
 	PCRE_DEFINES="$PCRE_DEFINES -DUSE_BCOPY"
 AC_SUBST(PCRE_DEFINES)
 
+### NLS macro
+AM_GNU_GETTEXT
+test $nls_cv_use_gnu_gettext = yes && CPPFLAGS="$CPPFLAGS -I../intl"
+
 ### sum up warnings
 if test "$cf_cv_termlib" = none ; then
 	if test "$found_ncurses" != yes; then
@@ -896,4 +1147,4 @@ fi
 
 ### Finally, build autoconf.h and the makefiles
 CFLAGS="$CFLAGS $EXTRA_CFLAGS"
-AC_OUTPUT(makefile pcre/Makefile src/Makefile)
+AC_OUTPUT(makefile intl/Makefile po/Makefile.in pcre/Makefile src/Makefile)
