snapshot of project "tin-beta", label v2_6_4-20240703

diff --git a/tools/tinlock b/tools/tinlock
--- a/tools/tinlock
+++ b/tools/tinlock
@@ -6,43 +6,43 @@ prog=/usr/local/bin/tin
 
 args=${1+"$@"}
 
-name=`basename $prog`
+name=`basename "$prog"`
 host=`hostname`
 pid=$$
-lock=$host"	"$pid
+lock="$host	$pid"
 
 if test -d ${TIN_HOMEDIR-"$HOME"} ; then
 	lockdir=${TIN_HOMEDIR-"$HOME"}/.tin
 	file=tinlock
 else
 	lockdir=${TMPDIR-/tmp}
-	if test -z $USER; then
-		if test -z $UID ; then
+	if test -z "$USER"; then
+		if test -z "$UID" ; then
 			UID=`id|sed 's,uid=\([0-9]\+\).*,\1,'`
 		fi
 	fi
 	file=tinlock.${USER-"$UID"}
 fi
 
-lockfile=$lockdir/$file
+lockfile="$lockdir/$file"
 
-if test -f $lockfile ; then
+if test -f "$lockfile" ; then
 	echo "Found \"$lockfile\"! Another $name running on:"
-	awk '{print $1" with pid: "$2"?"}' < $lockfile
+	awk '{print $1" with pid: "$2"?"}' < "$lockfile"
 	echo "(q)uit - start (r)ead-only - (d)elete lock and start normal."
 	IFS="       " read key
 	case $key in
 		[dD]*)
 			echo "Removing \"$lockfile\" and starting $name normal..."
-			rm -f $lockfile || (echo "Can't delete \"$lockfile\"" ; exit 1)
+			rm -f "$lockfile" || (echo "Can't delete \"$lockfile\"" ; exit 1)
 			trap "rm -f $lockfile; exit" 0 1 2 3 15
-			(echo $lock > $lockfile && $prog $args && rm -f $lockfile) || echo "Oops!"
+			(echo "$lock" > "$lockfile" && "$prog" "$args" && rm -f "$lockfile") || echo "Oops!"
 			;;
 		[rR]*)
 			echo "Starting $name in no-write (-X) mode..."
-			$prog -X $args
+			"$prog" -X "$args"
 			echo "There might still be copy(s) of $name running on:"
-			awk '{print $1" with pid: "$2}' < $lockfile
+			awk '{print $1" with pid: "$2}' < "$lockfile"
 			echo "If this is not the case remember to remove \"$lockfile\"."
 			;;
 		*)
@@ -52,5 +52,5 @@ if test -f $lockfile ; then
 	esac
 else
 	trap "rm -f $lockfile; exit" 0 1 2 3 15
-	(echo $lock > $lockfile && $prog $args && rm -f $lockfile) || echo "Oops!"
+	(echo "$lock" > "$lockfile" && "$prog" "$args" && rm -f "$lockfile") || echo "Oops!"
 fi
